#---Continue from REPOSITORY:TAG=ubuntu_sunplus:latest
FROM ubuntu_sunplus:latest

#---LABEL about the custom image
LABEL maintainer="hien@tibbo.com"
LABEL version="0.1"
LABEL description="Continue from image 'ubuntu_sunplus:latest', and run 'disk_preprep.sh'"

#---Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

#---Update local Git repository
RUN cd ~/LTPP3_ROOTFS && git pull

#---Run Prepreparation of Disk (before Chroot)
RUN cd ~ && ~/LTPP3_ROOTFS/disk_preprep.sh