#---Continue from REPOSITORY:TAG=ubuntu_base:latest
FROM ubuntu_base:latest

#---LABEL about the custom image
LABEL maintainer="hien@tibbo.com"
LABEL version="0.1"
LABEL description="Continue from 'ubuntu_base:latest' image, and install updates, upgrades, and required apps"

#---Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

#---Update and Upgrade
RUN apt-get -y update
RUN apt-get -y upgrade

#---Install required apps
RUN apt -y install	bison			    \
                    build-essential	    \
                    flex			    \ 
                    git			        \
                    libncurses5-dev     \
                    libssl-dev		    \
                    openssl			    \ 
                    qemu			    \ 
                    qemu-user-static    \ 
                    sshfs			    \
                    u-boot-tools	    \
                    wget                \
                    bc                  \
                    nano                \
                    vim                 \
                    curl