#---Continue from REPOSITORY:TAG=ubuntu_chroot:latest
FROM ubuntu_chroot:latest 

#---LABEL about the custom image
LABEL maintainer="hien@tibbo.com"
LABEL version="0.1"
LABEL description="Continue from image 'ubuntu_chroot:latest', and run 'build_BOOOT_BIN.sh'"

#---Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

#---Update local Git repository
RUN cd ~/LTPP3_ROOTFS && git pull

#---Run Prepreparation of Disk (before Chroot)
RUN cd ~ && ~/LTPP3_ROOTFS/build_BOOOT_BIN.sh