#---Continue from REPOSITORY:TAG=ubuntu_base:20.04
FROM ubuntu_base:20.04

#---LABEL about the custom image
LABEL maintainer="hien@tibbo.com"
LABEL version="0.1"
LABEL description="Continue from image ubuntu_base:20.04, and run build_BOOOT_BIN.sh"
LABEL NEW repository:tag="ubuntu_base_2323:20.04"

#---Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

#---Update local Git repository
#RUN cd ~/LTPP3_ROOTFS && git pull

#---Run Prepreparation of Disk (before Chroot)
#RUN cd ~ && ~/LTPP3_ROOTFS/build_BOOOT_BIN.sh
