#---Continue from REPOSITORY:TAG=ltps_sunplus:latest
FROM ltps_sunplus:latest

#---LABEL about the custom image
LABEL maintainer="hien@tibbo.com"
LABEL version="0.1"
LABEL description="Continue from image 'ltps_sunplus:latest'"
LABEL repository:tag="ltps_rootfs_test:test"

#---Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

#---Retrieve files from Git
RUN cd ~ && rm -rf LTPP3_ROOTFS

RUN cd ~ && git clone --branch fixonetimexec https://github.com/tibbotech/LTPP3_ROOTFS.git

#---Disk Prepreparation (before CHROOT)
RUN cd ~ && ~/LTPP3_ROOTFS/disk_preprep.sh

#---CHROOT
RUN cd ~ && ~/LTPP3_ROOTFS/chroot_rundisk.sh