#---Continue from REPOSITORY:TAG=ltps_sunplus:latest
FROM ltps_sunplus_env:test

#---LABEL about the custom image
LABEL maintainer="hien@tibbo.com"
LABEL version="0.1"
LABEL description="Continue from image 'ltps_sunplus_env:test'"
LABEL repository:tag="ltps_rootfs_env:test"

#---Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

#---Update local Git repository
RUN cd ~/LTPP3_ROOTFS && git pull

# ---Disk Prepreparation (before CHROOT)
RUN cd ~ && ~/LTPP3_ROOTFS/disk_preprep.sh

#---CHROOT
RUN cd ~ && ~/LTPP3_ROOTFS/chroot_rundisk.sh