#---Continue from REPOSITORY:TAG=ubuntu_diskpostprep_uart_buildbin:latest
FROM ubuntu_diskpostprep_uart_buildbin:latest

#---LABEL about the custom image
LABEL maintainer="hien@tibbo.com"
LABEL version="0.1"
LABEL description="Continue from image ubuntu_diskpostprep_uart_buildbin:latest, and run build_BOOOT_BIN.sh"
LABEL NEW repository:tag="ubuntu_diskpostprep_uart_buildbin_NEW:latest"

#---Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

#---Update local Git repository
#RUN cd ~/LTPP3_ROOTFS && git pull

#---Run Prepreparation of Disk (before Chroot)
#RUN cd ~ && ~/LTPP3_ROOTFS/build_BOOOT_BIN.sh
