#---Continue from REPOSITORY:TAG=ltps_init:latest
FROM ltps_init:latest

#---LABEL about the custom image
LABEL maintainer="hien@tibbo.com"
LABEL version="0.1"
LABEL description="Continue from image 'ltps_init:latest', and install & configure 'SUNPLUS'"
LABEL repository:tag="ltps_sunplus:latest"

#---Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

#---Set ARGUMENT to be passed via the docker command:
#---These arguments are used in the files:
#---1. docker_create_an_image_from_dockerfile.sh -> function: create_image__func
#---2. docker_create_images_from_dockerlist.sh -> function: create_image__func
ARG DOCKER_ARG1
ARG DOCKER_ARG2

#---Set ENVIRONMENT VARIABLE
#---The NAME of the defined environment variable(s) MUST be the same as
#   the variable(s) names which is(are) used in the script (e.g. sunplus_inst.sh)
#   to be run in the container
ENV CONTAINER_ENV1=${DOCKER_ARG1}
ENV CONTAINER_ENV2=${DOCKER_ARG2}

#---Retrieve files from Git
RUN cd ~ && git clone https://github.com/tibbotech/LTPP3_ROOTFS.git

#---Run Sunplus installation and Configuration
RUN cd ~ && ~/LTPP3_ROOTFS/sunplus_inst.sh