#---Continue from REPOSITORY:TAG=ltps_sunplus:latest
FROM ltps_sunplus:latest

#---LABEL about the custom image
LABEL maintainer="hien@tibbo.com"
LABEL version="0.1"
LABEL description="Continue from image 'ltps_sunplus:latest'"
LABEL repository:tag="ltps_rootfs:latest"

#---Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

#---Set ARGUMENT to be passed via the docker command:
#---These arguments are used in the files:
#---1. docker_create_an_image_from_dockerfile.sh -> function: create_image__func
#---2. docker_create_images_from_dockerlist.sh -> function: create_image__func
ARG DOCKER_ARG4
#---Set ENVIRONMENT VARIABLE TO BE PASSED INTO CONTAINER
#---The NAME of the defined environment variable(s) MUST be the same as
#   the variable(s) names which is(are) used in the script (e.g. sunplus_inst.sh)
#   to be run in the container
ENV CONTAINER_ENV4=${DOCKER_ARG4}

#---Update local Git repository
RUN cd ~/LTPP3_ROOTFS && git pull

# ---Disk Prepreparation (before CHROOT)
RUN cd ~ && ~/LTPP3_ROOTFS/disk_preprep.sh

#---CHROOT
RUN cd ~ && ~/LTPP3_ROOTFS/chroot_rundisk.sh