#---Continue from REPOSITORY:TAG=ltps_rootfs:latest
FROM ltps_rootfs:latest

#---LABEL about the custom image
LABEL maintainer="hien@tibbo.com"
LABEL version="0.1"
LABEL description="Continue from image 'ltps_rootfs:latest'"
LABEL repository:tag="ltps_rootfs_preferences:latest"

#---Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

#---Update local Git repository
RUN cd ~/LTPP3_ROOTFS && git pull

#---Run Prepreparation of Disk (AFTER Chroot)
RUN cd ~ && ~/LTPP3_ROOTFS/disk_postprep_uart.sh