#---Continue from REPOSITORY:TAG=ubuntu_chroot:latest
FROM ubuntu_chroot:latest

#---LABEL about the custom image
LABEL maintainer="hien@tibbo.com"
LABEL version="0.1"
LABEL description="Continue from image 'ubuntu_chroot:latest', and run 'disk_postprep_uart.sh'"
LABEL repository:tag="ubuntu_diskpostprep_uart:latest"

#---Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

#---Update local Git repository
RUN cd ~/LTPP3_ROOTFS && git pull

#---Run Prepreparation of Disk (AFTER Chroot)
RUN cd ~ && ~/LTPP3_ROOTFS/disk_postprep_uart.sh