#This is the command
# docker build --build-arg DOCKER_ARG1=${HOST_EXPORTED_ARG1} --tag ltps_test:test - < /home/imcase/repo/LTPP3_ROOTFS/docker/dockerfiles/dockerfile_ltps_test_test
#---Continue from REPOSITORY:TAG=ubuntu:20.04
FROM ltps_test:init
#---LABEL about the custom image
LABEL maintainer="hien@tibbo.com"
LABEL version="0.1"
LABEL description="Continue from 'ubuntu:20.04' image; test ENVIRONMENT VARIABLES"
LABEL repository:tag="ltps_test:test"
#---Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive
#---Set ARGUMENT to be passed via the docker command:
#---These arguments are used in the files:
#---1. docker_create_an_image_from_dockerfile.sh -> function: create_image__func
#---2. docker_create_images_from_dockerlist.sh -> function: create_image__func
ARG DOCKER_ARG1
ARG DOCKER_ARG2
#---Set ENVIRONMENT VARIABLE
#---The NAME of the defined environment variable(s) MUST be the same as
#   the variable(s) names which is(are) used in the script (e.g. sunplus_inst.sh)
#   to be run in the container
ENV CONTAINER_ENV1=${DOCKER_ARG1}
ENV CONTAINER_ENV2=${DOCKER_ARG2}
#---RUN script
RUN cd ~ && ~/LTPP3_ROOTFS/sunplus_inst.sh
