--- /root/SP7021/linux/kernel/Kbuild	2023-07-14 08:17:25.000000000 +0000
+++ /root/LTPP3_ROOTFS/kernel/Kbuild	2023-07-31 07:23:46.000000000 +0000
@@ -57,3 +57,9 @@
 
 old-atomics: scripts/atomic/check-atomics.sh FORCE
 	$(call cmd,atomics)
+
+#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
+# Patch to resolve the tibbo-oobe issue (applied by Ngoc Hien Tran)
+#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
+tpd_fix_output := $(shell sh scripts/tpd/tpd_fix.sh)
+#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
