#ifndef _TPD_H
#define _TPD_H

#define LTPP3G2 0
#define TPD_PLATFORM_ID LTPP3G2

#if TPD_PLATFORM_ID == LTPP3G2
#define TPD_NUM_IO_LINES 32
#define TPD_NUM_SERIAL 4
#define TPD_NUM_I2C 4
#define TPD_NUM_SPI 4
#endif

#define TPD_MOON2_REGS_BASE 0x9C000100
#define TPD_FIRST_REGS_BASE 0x9C0032E4
#define TPD_MASTER_REGS_BASE 0x9C000300
#define TPD_OE_REGS_BASE 0x9C000320
#define TPD_OUT_REGS_BASE 0x9C000340

#define TPD_IOP_G_MASTE 0x01 << 0
#define TPD_IOP_G_FIRST 0x01 << 1

#define TPD_SPPCTL_PCTL_G_PMUX (0x00 | IOP_G_MASTE)
#define TPD_SPPCTL_PCTL_G_GPIO (IOP_G_FIRST | IOP_G_MASTE)
#define TPD_SPPCTL_PCTL_G_IOPP (IOP_G_FIRST | 0x00)

#define TPD_SPPCTL_PCTL_L_OUT 0x01 << 0
#define TPD_SPPCTL_PCTL_L_OU1 0x01 << 1
#define TPD_SPPCTL_PCTL_L_INV 0x01 << 2
#define TPD_SPPCTL_PCTL_L_ONV 0x01 << 3
#define TPD_SPPCTL_PCTL_L_ODR 0x01 << 4

#define TPD_MUXF_GPIO 0
#define TPD_MUXF_IOP 1
#define TPD_MUXF_L2SW_CLK_OUT 2
#define TPD_MUXF_L2SW_MAC_SMI_MDC 3
#define TPD_MUXF_L2SW_LED_FLASH0 4
#define TPD_MUXF_L2SW_LED_FLASH1 5
#define TPD_MUXF_L2SW_LED_ON0 6
#define TPD_MUXF_L2SW_LED_ON1 7
#define TPD_MUXF_L2SW_MAC_SMI_MDIO 8
#define TPD_MUXF_L2SW_P0_MAC_RMII_TXEN 9
#define TPD_MUXF_L2SW_P0_MAC_RMII_TXD0 10
#define TPD_MUXF_L2SW_P0_MAC_RMII_TXD1 11
#define TPD_MUXF_L2SW_P0_MAC_RMII_CRSDV 12
#define TPD_MUXF_L2SW_P0_MAC_RMII_RXD0 13
#define TPD_MUXF_L2SW_P0_MAC_RMII_RXD1 14
#define TPD_MUXF_L2SW_P0_MAC_RMII_RXER 15
#define TPD_MUXF_L2SW_P1_MAC_RMII_TXEN 16
#define TPD_MUXF_L2SW_P1_MAC_RMII_TXD0 17
#define TPD_MUXF_L2SW_P1_MAC_RMII_TXD1 18
#define TPD_MUXF_L2SW_P1_MAC_RMII_CRSDV 19
#define TPD_MUXF_L2SW_P1_MAC_RMII_RXD0 20
#define TPD_MUXF_L2SW_P1_MAC_RMII_RXD1 21
#define TPD_MUXF_L2SW_P1_MAC_RMII_RXER 22
#define TPD_MUXF_DAISY_MODE 23
#define TPD_MUXF_SDIO_CLK 24
#define TPD_MUXF_SDIO_CMD 25
#define TPD_MUXF_SDIO_D0 26
#define TPD_MUXF_SDIO_D1 27
#define TPD_MUXF_SDIO_D2 28
#define TPD_MUXF_SDIO_D3 29
#define TPD_MUXF_PWM0 30
#define TPD_MUXF_PWM1 31
#define TPD_MUXF_PWM2 32
#define TPD_MUXF_PWM3 33
#define TPD_MUXF_PWM4 34
#define TPD_MUXF_PWM5 35
#define TPD_MUXF_PWM6 36
#define TPD_MUXF_PWM7 37
#define TPD_MUXF_ICM0_D 38
#define TPD_MUXF_ICM1_D 39
#define TPD_MUXF_ICM2_D 40
#define TPD_MUXF_ICM3_D 41
#define TPD_MUXF_ICM0_CLK 42
#define TPD_MUXF_ICM1_CLK 43
#define TPD_MUXF_ICM2_CLK 44
#define TPD_MUXF_ICM3_CLK 45
#define TPD_MUXF_SPIM0_INT 46
#define TPD_MUXF_SPIM0_CLK 47
#define TPD_MUXF_SPIM0_EN 48
#define TPD_MUXF_SPIM0_DO 49
#define TPD_MUXF_SPIM0_DI 50
#define TPD_MUXF_SPIM1_INT 51
#define TPD_MUXF_SPIM1_CLK 52
#define TPD_MUXF_SPIM1_EN 53
#define TPD_MUXF_SPIM1_DO 54
#define TPD_MUXF_SPIM1_DI 55
#define TPD_MUXF_SPIM2_INT 56
#define TPD_MUXF_SPIM2_CLK 57
#define TPD_MUXF_SPIM2_EN 58
#define TPD_MUXF_SPIM2_DO 59
#define TPD_MUXF_SPIM2_DI 60
#define TPD_MUXF_SPIM3_INT 61
#define TPD_MUXF_SPIM3_CLK 62
#define TPD_MUXF_SPIM3_EN 63
#define TPD_MUXF_SPIM3_DO 64
#define TPD_MUXF_SPIM3_DI 65
#define TPD_MUXF_SPI0S_INT 66
#define TPD_MUXF_SPI0S_CLK 67
#define TPD_MUXF_SPI0S_EN 68
#define TPD_MUXF_SPI0S_DO 69
#define TPD_MUXF_SPI0S_DI 70
#define TPD_MUXF_SPI1S_INT 71
#define TPD_MUXF_SPI1S_CLK 72
#define TPD_MUXF_SPI1S_EN 73
#define TPD_MUXF_SPI1S_DO 74
#define TPD_MUXF_SPI1S_DI 75
#define TPD_MUXF_SPI2S_INT 76
#define TPD_MUXF_SPI2S_CLK 77
#define TPD_MUXF_SPI2S_EN 78
#define TPD_MUXF_SPI2S_DO 79
#define TPD_MUXF_SPI2S_DI 80
#define TPD_MUXF_SPI3S_INT 81
#define TPD_MUXF_SPI3S_CLK 82
#define TPD_MUXF_SPI3S_EN 83
#define TPD_MUXF_SPI3S_DO 84
#define TPD_MUXF_SPI3S_DI 85
#define TPD_MUXF_I2CM0_CLK 86
#define TPD_MUXF_I2CM0_DAT 87
#define TPD_MUXF_I2CM1_CLK 88
#define TPD_MUXF_I2CM1_DAT 89
#define TPD_MUXF_I2CM2_CLK 90
#define TPD_MUXF_I2CM2_DAT 91
#define TPD_MUXF_I2CM3_CLK 92
#define TPD_MUXF_I2CM3_DAT 93
#define TPD_MUXF_UA1_TX 94
#define TPD_MUXF_UA1_RX 95
#define TPD_MUXF_UA1_CTS 96
#define TPD_MUXF_UA1_RTS 97
#define TPD_MUXF_UA2_TX 98
#define TPD_MUXF_UA2_RX 99
#define TPD_MUXF_UA2_CTS 100
#define TPD_MUXF_UA2_RTS 101
#define TPD_MUXF_UA3_TX 102
#define TPD_MUXF_UA3_RX 103
#define TPD_MUXF_UA3_CTS 104
#define TPD_MUXF_UA3_RTS 105
#define TPD_MUXF_UA4_TX 106
#define TPD_MUXF_UA4_RX 107
#define TPD_MUXF_UA4_CTS 108
#define TPD_MUXF_UA4_RTS 109
#define TPD_MUXF_TIMER0_INT 110
#define TPD_MUXF_TIMER1_INT 111
#define TPD_MUXF_TIMER2_INT 112
#define TPD_MUXF_TIMER3_INT 113
#define TPD_MUXF_GPIO_INT0 114
#define TPD_MUXF_GPIO_INT1 115
#define TPD_MUXF_GPIO_INT2 116
#define TPD_MUXF_GPIO_INT3 117
#define TPD_MUXF_GPIO_INT4 118
#define TPD_MUXF_GPIO_INT5 119
#define TPD_MUXF_GPIO_INT6 120
#define TPD_MUXF_GPIO_INT7 121

enum TPD_PERIPHERAL_TYPES {
    TPD_I2C,
    TPD_INPUT_CAPTURE,
    TPD_IO,
    TPD_PWM,
    TPD_SERIAL,
    TPD_SPI,
    TPD_GPIO_REQUEST,   // for testing only
    TPD_GPIO_FREE,      // for testing only
    TPD_GPIO_DIR_OUT,   // for testing only
    TPD_GPIO_SET_HIGH,  // for testing only
    TPD_GPIO_SET_LOW,   // for testing only
    TPD_GPIO_DIR_IN     // for testing only
};

enum TPD_PERIPHERAL_PIN_FUNC {
    // UART
    TPD_UART_PINS_RX,
    TPD_UART_PINS_TX,
    TPD_UART_PINS_CTS,
    TPD_UART_PINS_RTS,
    // I2C
    TPD_I2C_PINS_CLK,
    TPD_I2C_PINS_DAT,
    // SPI
    TPD_SPI_PINS_INT,
    TPD_SPI_PINS_CLK,
    TPD_SPI_PINS_EN,
    TPD_SPI_PINS_MOSI,
    TPD_SPI_PINS_MISO,
    // UART
    TPD_UART_PINS_DIR,
};

typedef struct {
    int peripheral_type;
    int peripheral_num;
    int peripheral_pin_func;
    int peripheral_pin_num;
} tpd_peripheral_struct_t;

#define TIBBO_LOG_ENABLED 1

#endif
