#!/bin/bash
#---CONSTANTS
FG_RESET="\e[0;0m"
FG_LIGHTBLUE="\e[30;38;5;45m"
FG_GREY="\e[30;38;5;246m"
FG_RED9="\e[30;38;5;9m"
BLINK="\e[5m"

#---ISPBOOOT.BIN VERSION
ispboootbin_version_txt_fpath="/etc/tibbo/version/ispboootbin_version.txt"
ispboootbin_version_retrieved=""
if [[ -f "${ispboootbin_version_txt_fpath}" ]]; then
    ispboootbin_version_retrieved=$(cat "${ispboootbin_version_txt_fpath}")
    ispboootbin_version_retrieved_print="${FG_LIGHTBLUE}${ispboootbin_version_retrieved}${FG_RESET}"

    if [[ -z "${ispboootbin_version_retrieved}" ]]; then
        ispboootbin_version_retrieved_print="file ${FG_GREY}${ispboootbin_version_txt_fpath}${FG_RESET} contains ${FG_RED9}NO${FG_RESET} version"
    fi
else
    ispboootbin_version_retrieved_print="file ${FG_GREY}${ispboootbin_version_txt_fpath} ${FG_RED9}NOT${FG_RESET} found"
fi

#---PRINT
echo -e "\r"
echo "*********************************************************************"
echo -e "% ISPBOOOT.BIN VERSION: ${ispboootbin_version_retrieved_print}"
echo "*********************************************************************"
echo -e "\r"
