#!/bin/bash
#---CONSTANTS
FG_RESET="\e[0;0m"
FG_DARKBLUE="\e[30;38;5;33m"
FG_LIGHTBLUE=$'\e[30;38;5;45m'
FG_GREY="\e[30;38;5;246m"
BLINK="\e[5m"

#---CHECK IF WLAN IS PRESENT
wlan_interfacename=$(ip a | grep -o "wlan.*" | head -n1 | awk '{print $1}' | cut -d":" -f1)
if [[ -z "${wlan_interfacename}" ]]; then
    exit;
fi

#---PRINT
echo -e "\r"
echo "*********************************************************************"
echo -e "% ${wlan_interfacename} is ${BLINK}present${FG_RESET}"
echo "*********************************************************************"
echo -e "% ${FG_GREY}Execute ${FG_LIGHTBLUE}sudo tb_wlan_mainmenu${FG_GREY} to configure ${FG_DARKBLUE}WLAN${FG_RESET}"
echo "*********************************************************************"
echo -e "\r"
