--- Makefile.old	2023-11-14 09:09:48.000000000 +0000
+++ Makefile	2024-04-15 03:04:54.000000000 +0000
@@ -189,3 +189,17 @@
 obj-$(CONFIG_INTERCONNECT)	+= interconnect/
 obj-$(CONFIG_COUNTER)		+= counter/
 obj-$(CONFIG_MOST)		+= most/
+
+################################################################################
+# Added by Ngoc Hien Tran
+################################################################################
+# REASON:
+#	To address the issue that the module tpd.ko MUST be created during
+#		the ISPBOOOT.BIN build-process.
+# NOTE: 
+#	This line is necessary to INCLUDE the 'tpd' folder,
+#		which is part of directory (/root/SP7021/linux/kernel/drivers).
+# NOTE: 
+#	Fullpath is of the 'tpd' folder is (/root/SP7021/linux/kernel/drivers/tpd).
+################################################################################
+obj-$(CONFIG_TPD) += tpd/
